name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  pytool:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/pytool
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run pipeline
        run: |
          make clean
          make install
          make lint
          make run
